webpack-contrib/postcss-loader

index.js

This fixes the broken less source maps (#15).

support json source maps - fixes #15

---

README.md

Fix cssnext usage in examples

---

README.md

misspelling
To make them work proper*L*y,

Update README.md misspelling

---

README.md

I've just noticed some minor problems in the readme copy.

Fix typos in the readme file

---

README.md

Hi, fixed a bit confusing moment ^_^

update readme config section - loaders order

---

index.js
package.json

Watch Config (postcss.config.js)

---

index.js

Remove webpack Plugin warning (#179)

---

README.md

docs(README): add missing comma

---

README.md
lib/index.js

Tiny change, thanks for reviewing!

fix: misspelling in warnings

---

README.md

docs(README): add loader description

---

lib/Error.js

refactor(lib/Error): remove unused branches

---

lib/options.js
lib/options.json
test/options/__snapshots__/plugins.test.js.snap
test/options/plugins.test.js

fix(lib/options): handle `{Object}` return (`options.plugins`)

---

lib/index.js

fix(index): filter `ident` (`options.ident`)

---

README.md

docs(README): fix lint in example

---

package.json

[Jest #6766](https://github.com/facebook/jest/issues/6766) 
- None

ci(package): run tests in an explicit environment (`jest --env=node`)

---

appveyor.yml

ci(appveyor): readd Appveyor CI

---

.travis.yml
lib/index.js
test/fixtures/config/context/plugin.js
test/loader.test.js
test/options/config.test.js
test/options/exec.test.js
test/options/parser.test.js
test/options/plugins.test.js
test/options/sourceMap.test.js
test/options/stringifier.test.js
test/options/syntax.test.js

ci(travis): build stages

---

README.md
package-lock.json
package.json
src/index.js
test/fixtures/scss/index.js
test/fixtures/scss/style.scss
test/options/__snapshots__/sourceMap.test.js.snap
test/options/sourceMap.test.js

…l option
Enables default generation of source maps depends on the `devtool` option
Edit readme
No
No

Enables default generation of source maps depends on the devtool option

---

README.md
package-lock.json
package.json
src/options.json
test/__snapshots__/validate-options.test.js.snap
test/options/__snapshots__/parser.test.js.snap
test/options/__snapshots__/stringifier.test.js.snap
test/options/parser.test.js
test/options/stringifier.test.js
test/validate-options.test.js

Fix postcss options types

---

package-lock.json
package.json
src/index.js
src/utils.js
test/fixtures/less/index.js
test/fixtures/less/style.less
test/helpers/getCodeFromBundle.js
test/options/__snapshots__/sourceMap.test.js.snap
test/options/sourceMap.test.js

Improved source map processing
No
No

Refactor sourcemap paths

---

package-lock.json
package.json

chore: remove unnecessary dev deps

---

src/utils.js
test/__snapshots__/plugins.test.js.snap
test/fixtures/plugin/default-other-plugin.js
test/plugins.test.js

`default` export for plugins
No
No

fix: `default` export for plugins

---

package-lock.json
package.json
src/index.js
test/__snapshots__/execute.test.js.snap
test/__snapshots__/loader.test.js.snap
test/execute.test.js
test/helpers/astLoader.js
test/loader.test.js

feat: reuse AST from other loaders

---

README.md
src/options.json
test/__snapshots__/loader.test.js.snap
test/__snapshots__/validate-options.test.js.snap
test/loader.test.js

improve readme
No
Feel free to open new issue if something was not documented or misleading

Docs improve readme

---

README.md

docs: fix the `config` option usage

---

src/utils.js
test/config-autoload.test.js

It is feature and bug fix
No
No

refactor: use `this.addBuildDependency` for tracking configurations

---

README.md
src/index.js
src/options.json
src/utils.js
test/__snapshots__/implementation.test.js.snap
test/__snapshots__/loader.test.js.snap
test/__snapshots__/validate-options.test.js.snap
test/implementation.test.js
test/validate-options.test.js

`implementation` option string value support added
No
No

feat: implementation option string value support added

---

src/utils.js
test/config-autoload.test.js

fix: watching configuration

---

src/utils.js

Clean code, reduce size and remove repetition.
I don't think so.
-

refactor: loadPlugin

---

jest.config.js
package-lock.json
package.json
test/__snapshots__/implementation.test.js.snap
test/__snapshots__/loader.test.js.snap
test/config-autoload.test.js
test/fixtures/config-autoload/ts/array/postcss.config.ts
test/fixtures/config-autoload/ts/object/postcss.config.ts
test/implementation.test.js
test/loader.test.js

update tests and fix tests
No
No

chore(deps): update

---

src/utils.js

avoid import cosmiconfig typescript loader when no ts-node
fixes #634
No
No

fix: typescript loader

---

src/utils.js

fix: ts-node loading

---

src/utils.js

fixes https://github.com/webpack-contrib/postcss-loader/pull/641/
No
/cc @Vrainy thank you for report about this

fix: memory leak

---

.cspell.json
package-lock.json
package.json
src/utils.js
test/config-autoload.test.js
test/fixtures/config-autoload/ts/array-mts/imports/section.css
test/fixtures/config-autoload/ts/array-mts/index.css
test/fixtures/config-autoload/ts/array-mts/index.js
test/fixtures/config-autoload/ts/array-mts/postcss.config.mts

fixes https://github.com/webpack-contrib/postcss-loader/issues/646
Avoid extra big dependecies, also fix problems for `cjs` and `mjs`
Hope no
No

feat: use `jiti` for typescript configurations
