index.js

This fixes source mapping when used with sass-loader.
Also, we don't want to map to the postcss generated source, we want to map to the pre-postcss source, so this is also an improvement for CSS source maps.
Inline source maps can be generated using `devtool: 'inline-source-map'`.

Better sourcemaps support

---

index.js

PostCSS was throwing "Unsupported previous source map format" error in situations where a sass file was compiled without any output. (For example a scss file that contained an empty selector.)

Fixed invalid sourcemap exception

---

README.md

Hello @ai and sorry for the delay.
I updated the readme... Hope it's clear enough.

Promote use of postcss functions

---

CHANGELOG.md
README.md
index.js

I didn’t add any test yet because:
- it’s a trivial change
- adding test(s) for this trivial change will require to refactor all
the tests in order to be able to have several webpack configs
- I am lazy and already made the appropriate change in postcss-import
that took me some time :)
Close #31
Maybe it's time to release 1.0 ?

Added new API to facilitate postcss-import dependencies tracking with webpack

---

README.md

Add info about integration with CSS Modules

---

index.js

From https://webpack.github.io/docs/how-to-write-a-loader.html, on the subject of loaders returning sourcemaps:
> The loader is expected to give back one or two values. ... The second optional value is a SourceMap as JavaScript object.
However, postcss-loader returns an instance of SourceMapGenerator
https://github.com/postcss/postcss-loader/blob/master/index.js#L51
This may break subsequent loaders that are expecting to receive a sourcemap.

Return proper sourcemap instead of SourceMapGenerator

---

README.md

- Add brief instructional step for installing this module.
- Add notice about potential need to install plugins used in the example implementation.

Update README.md to include install instructions

---

README.md
index.js

In its current implementation, `parser`, `syntax`, and `stringifier` can only be passed as string which are required internally. This patch allows users to pass in any of these options as a function instead of a string, which is important to be able to do if the option is passed from elsewhere and not required directly as is done internally.
This patch is made in a manner that is non-breaking, although honestly making a breaking change to the way options are handled would provide a much cleaner syntax and easier user experience. If you're open to breaking changes, I'd be happy to modify this -- my proposal would be to just have the postcss webpack option always ask for an object or function that returns an object. This way we have a flexible data structure that's able to accommodate …

Add capability to pass other options as function

---

README.md

A comment in the example code refers to the CSSWring plugin but it should be PreCSS instead.

Update README.md to fix example

---

index.js

postcss-loader?sourceMap=inline will output css and it's inline sourcemap. It's useful to angular 2's component styles.

add inline sourcemap support, it's useful to angular 2

---

index.js
package.json

I used `babel-code-frame` package formatting syntax errors code frames. That makes it consistent with Babel output which is I think very important as it makes it less cognitive efforts to recognize and process the error. Also code frames are a little bit fancies now (shows the line numebrs) so probably PostCSS itself should adopt this style.
You can also see that there's no duplicated filename in error message as webpack already print module name.
Before:
After:

Consistent format for CSS syntax errors

---

README.md
index.js
test/test.js
test/webpack-plugins/rewrite.js
test/webpack.config.js

This pull request introduces a new feature.
It allows third party webpack plugins to add or remove postcss plugins using the `postcss-loader-before-processing` event (using the webpack built in plugin system).
An example can be seen here:
https://github.com/jantimon/postcss-loader/blob/33436d715119258053e5459b7cfde26eeecd0aa1/test/webpack-plugins/rewrite.js
Motivation:
There are cases where a postcss plugin is very tight cupeled with a webpack plugin as it has to access the webpack internals.
In this case it would be nice if this webpack could also add its postcss part to the loader.

Add postcss-loader-before-processing event

---

index.js

In conjunction with bluebird, I get a couple of Warnings:
> `Warning: a promise was created in a handler at usr/app/node_modules/postcss-loader/index.js:100:13 but was not returned from it, see http://goo.gl/rRqMUw`
[Documentation](http://goo.gl/rRqMUw) states that one should at least `return null` to "signal that we didn't forget to return".

Runaway promise

---

index.js
test/cases/exec.js
test/test.js

An `exec` flag can be provided to the loader query or webpack config. This instructs the loader to load the source using `exec`. This enhances the previous behavior which was to check that the loader query parser was strictly equal to `postcss-js`.
This fixes an issue where the `postcss-js` parser cannot be specified through the webpack postcss config option.
This also enables parsers other than `postcss-js` to receive executed module results.

Allow control over loader `exec`.

---

index.js

That way loader will not be fully functional when used with happypack, but at least without a crash.
Before:
```
ERROR in ./main.css
Module build failed: Error: Cannot read property 'applyPluginsWaterfall' of undefined
TypeError: Cannot read property 'applyPluginsWaterfall' of undefined
```
After
```
WARNING in ./main.css
this._compilation is not available thus `postcss-loader-before-processing` is not supported
```

Gracefully handle lack of compilation object

---

index.js

When `webpack@2` lands there will no longer be any `this.options`. Since query can now be a vanilla object instead of a string, having `options` reside in query is a quick, non-destructive fix.
See:
* https://github.com/webpack/extract-text-webpack-plugin/pull/266
* https://github.com/webpack-config/webpack-config-postcss/pull/10

Allow `options` via `query`.

---

README.md

Some examples was using the option loader for an array of loaders, but the option should be on plural when its value is an array. 
This PR fixes that.

Fix wrong notation for loaders option on README

---

index.js

This resolves a bug in which the webpack loader context was not being passed correctly to the options parsing function.

Fix loader context

---

package.json

This module requires `postcss-load-config` which in turn requires `postcss-load-plugins` and `postcss-load-options`, all three of these repos have a NodeJS & NPM minimum requirement:
• "engines": { "node": ">=0.12", "npm": ">=3" },`
https://github.com/michael-ciniawsky/postcss-load-config/blob/master/package.json#L5
https://github.com/michael-ciniawsky/postcss-load-plugins/blob/master/package.json#L5
https://github.com/michael-ciniawsky/postcss-load-options/blob/master/package.json#L5
To prevent warnings when using this module this repo should also follow the same min req.

Update minimum NodeJS and NPM versions required

---

index.js

In the previous code, PRed code didn't meet the convention. So, I fixed it here. 
**For the readers who googled this document.**
We discussed about the configuration path for the postcss-loader at #143. If you want to know how it works, read that document.

New PR that meets the convention. 

---

index.js

I'm unable to write a test for it as you compile the tests, so webpack handles the path for you... Ideas?
The test I wrote:
```js
it('allows to change config path with absolute path', function () {
// eslint-disable-next-line no-path-concat
var css = require('!raw-loader' +
'!../?config=' +
__dirname + '/cases/config/postcss.config.js' +
'!./cases/style.css');
expect(css).toEqual('a { color: black }\n');
});
```

Allow absolute path as config option

---

README.md

postcss-js parser produce wrapped styles, adding description to fix this problem

Adding description of using postcss-js parser with babel 6 compiler

---

index.js

Hi there! So I ran into a situation where I need to require the parser myself and pass it in, rather than having it required internally, so I added this option. I couldn't quickly get my head around how the test suite works, but if you give me a push in the right direction I'd be happy to add a test for this. Meanwhile, it is a progressive upgrade, so it won't break any existing functionality.

Don't force internal requires of options

---

index.js

Because no need to and some other tools might use `--config` to load their config file.

Do not load config file from `--config`

---

README.md

cssnext@1.8.4: cssnext is now postcss-cssnext. cssnext is deprecated. See postcss-cssnext migration guide http://cssnext.io/postcss/

cssnext to postcss-cssnext

---

lib/index.js

Based on https://github.com/postcss/postcss-loader/pull/234#issuecomment-308486892

refactor: sanitizing `from` and `to` options (`postcss.config.js`)

---

lib/index.js

I'm getting a runaway promise warning:
```
Warning: a promise was created in a handler at /Users/jmclean/projects/node-graphql-demo/node_modules/postcss-loader/lib/index.js:173:16 but was not returned from it, see http://goo.gl/rRqMUw
at new Promise (/Users/jmclean/projects/node-graphql-demo/node_modules/bluebird/js/release/promise.js:77:14)
```
Seems that the loader returns undefined in certain situations, falling back to null fixes it and seems to be the recommended practice from the Bluebird docs: http://goo.gl/rRqMUw
There was a similar fix, about a year ago. #95

fix(index): runaway promise

---

README.md

Prevents throwing the warning "postcss-cssnext found a duplicate plugin ('autoprefixer') in your postcss plugins. This might be inefficient. You should remove 'autoprefixer' from your postcss plugin list since it's already included by postcss-cssnext."

docs(README): remove `autoprefixer` from example

---

README.md

docs(README): readd `ident: postcss` to examples (`options.ident`)

---

lib/options.json
test/loader.test.js
test/options/__snapshots__/parser.test.js.snap
test/options/__snapshots__/stringifier.test.js.snap
test/options/__snapshots__/syntax.test.js.snap
test/options/parser.test.js
test/options/stringifier.test.js
test/options/syntax.test.js

---
---
---
- Fixes `#1`
---
> _Put an `x` in the boxes that apply._

fix(schema): allow to pass an `{Object}` (`options.syntax/options.stringifier`)

---

README.md

[README](https://github.com/michael-ciniawsky/postcss-loader/blob/docs/README.md)
---
---
---

docs(README): add `option` types && links

---

README.md

---
Fixed a link in the README.
---
---
N/A
---
> _Put an `x` in the boxes that apply._

docs(README): fix broken link (`importLoaders`)

---

test/options/__snapshots__/config.test.js.snap
test/options/config.test.js

Hello,
I was just trying to figure out for a long time now, why my postcss-config is not taken into account, when using postcss-loader with webpack.
I dug into the loader and found this: https://github.com/postcss/postcss-loader/blob/master/lib/index.js#L53-L65, that is why my setup is not working.
Variable length has in this case value of 1, therefore return at line L65 and not using the postcssrc.
```
{
loader: 'postcss-loader',
options: {
sourceMap: true,
ident: 'postcss',
config: {
path: paths.DIR.ROOT,
},
},
};
```

test: ident && config not working

---

lib/index.js

As per the `loader-utils` documentation ([here](https://github.com/webpack/loader-utils#getoptions)),  the options object should not be modified directly.  Doing so causes the loader parameter of a `plugins` option function to only be run once at the first use of the loader.  This effectively causes the loader parameter to be useless as it cannot be used to retrieve information about the actual resource being used (i.e., `loader.resourcePath`, etc.) instead it will always point to the first resource the loader handled.  This PR makes a copy of the options object returned from `getOptions`.
---
---
---
---

fix(index): copy loader `options` before modifying

---

lib/index.js

---
---
---
> ℹ️  What issue (if any) are closed by your PR ?
- Fixes #227 
---

feat(index): pass `root` && `messages` as metadata for other loaders

---

README.md

> ℹ️  This just fixes link in table in README 
---
---
---
- Fixes `#1`
---
> _Put an `x` in the boxes that apply._

docs(README): fix source map anchor link in options table

---

lib/index.js
test/options/__snapshots__/sourceMap.test.js.snap
test/options/sourceMap.test.js

When passing `to` it truncates the output source map file path to just the path base name. By removing this value the paths are now correct.
The implementation of this logic is found [here](https://github.com/postcss/postcss/blob/master/lib/map-generator.es6#L179-L195)
---
---
---
- None
---
> ℹ️  You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. This is …

fix(index): don't set `to` value (`options`)

---

lib/options.json

Prevents unsupported options in webpack config. Unknown properties will cause a compilation error:
```
Module build failed: ValidationError: PostCSS Loader Invalid Options
options['other'] is an invalid additional property
```
---
---
---

fix(options): disallow additional properties and add `ident` to validation

---

lib/index.js
test/fixtures/config/context/plugin.js
test/fixtures/config/context/postcss.config.js
test/options/config.test.js

---
---
---
- Fixes `#354`
---
> _Put an `x` in the boxes that apply._
- [] Lint and unit …

fix: restore loader object in postcss config context

---

README.md
lib/index.js

Currently as long as there is a source map passed from an upstream loader (e.g. `vue-loader`), `postcss-loader` warns about sourceMap being discarded even when the `sourceMap` option is explicitly set to `false`. It should only warn when the option is "not set".
---
---
---
N/A
---
> ℹ️ …

fix(index): remove `sourceMap` warning

---

lib/index.js
package.json

Memory leak(s) in `postcss-load-config =< v1.0.0` 
---
---
---
- None  ([webpack #6929](https://github.com/webpack/webpack/issues/6929))
---

fix(package): config memory leak(s)

---

README.md

The description for `path` option in **README.md** is a bit misleading. It says `PostCSS Config Path` while in fact it sets only the directory where **postcss.config.js** will be looked for. 
It leads to a confusion, because users may think that they can set arbitrary name for their config file.
---
---
---
---

docs(README): clarify `path` option description (`options.config.path`)

---

README.md

Updated Url's in README to use https and resolve external url redirects if there were any
---

docs(README): resolve http redirects and use https

---

README.md

Replacing extract-text-plugin to mini-css-extract-plugin in the README's examples section
---
---
- Fixes #372

docs(README): update extract CSS example

---

README.md

I have replaced the mentions of [postcss-cssnext](https://github.com/MoOx/postcss-cssnext) with [postcss-preset-env](https://github.com/csstools/postcss-preset-env) since cssnext is deprecated.
---
---
---
- Fixes `#376`
---
> ℹ️  You can also fill these out after creating the PR. If …

docs(README): replace `postcss-cssnext` with `postcss-preset-env`

---

package.json

```
BREAKING CHANGE: requires `node >= v6.0.0`
```
- Fixes #374

chore(package): update `postcss` v6.0.0...7.0.0 (`dependencies`)

---

README.md

A follow-up PR to #379 
- None

docs(README): add autoprefixing example

---

README.md

Minor docs change to fix a broken link

docs(README): fix broken `context` link

---

src/index.js
test/options/__snapshots__/exec.test.js.snap
test/options/exec.test.js

fix: exec option for @webpack5

---

src/index.js
test/__snapshots__/loader.test.js.snap
test/helpers/getCodeFromBundle.js
test/helpers/getCompiler.js
test/helpers/testLoader.js
test/options/__snapshots__/config.test.js.snap
test/options/__snapshots__/exec.test.js.snap
test/options/__snapshots__/parser.test.js.snap
test/options/__snapshots__/plugins.test.js.snap
test/options/__snapshots__/sourceMap.test.js.snap
test/options/__snapshots__/stringifier.test.js.snap
test/options/__snapshots__/syntax.test.js.snap
test/options/exec.test.js
test/options/parser.test.js
test/options/syntax.test.js
test/validate-options.test.js

Remove export code
Yes.
if you want to get сss, use `css-loader`. In other cases, you can use `raw-loader`.
---
Loader should not change type of output based on index in `loaders`, it is not cacache, and can lead to very strange errors

Remove export code

---

README.md

Changes the usage documentation with respect to webpack loader order
None

docs(readme): change order of usage

---

README.md
src/index.js
src/utils.js
test/fixtures/css/plugins.config.js
test/options/__snapshots__/plugins.test.js.snap
test/options/plugins.test.js

It is possible to disable the plugin specified in the config.
No
No

The ability to disable plugins

---

src/index.js
test/__snapshots__/loader.test.js.snap
test/loader.test.js

Emit asset from messages

---

README.md

Adds to the readme how to emit an asset

---

README.md
test/fixtures/config/context/plugin.js
test/options/__snapshots__/config.test.js.snap
test/options/config.test.js

Adds to the readme how add dependency

---

src/utils.js
test/options/__snapshots__/parser.test.js.snap
test/options/__snapshots__/stringifier.test.js.snap
test/options/__snapshots__/syntax.test.js.snap

fix regressions in refactor
No
No

refactor: code

---

README.md
src/index.js
src/options.json
test/__snapshots__/validate-options.test.js.snap
test/options/__snapshots__/postcssOptins.test.js.snap
test/options/__snapshots__/sourceMap.test.js.snap
test/options/postcssOptins.test.js
test/options/sourceMap.test.js
test/validate-options.test.js

BREAKING CHANGE: the `inline` value was removed for the `sourceMap` option, please use `{ map: { inline: true, annotation: false } }` to achieve this
No need misleading options, also it is break source maps in many cases, but you still can achieve this
Yes
No

refactor: removed `inline` value for the `sourceMap` option

---

src/index.js

It is may create situation with false positive caching
Potential yes, but it is bug fix
No

refactor: do not pass meta from other loaders

---

package-lock.json
package.json
src/index.js
test/options/__snapshots__/sourceMap.test.js.snap
test/options/sourceMap.test.js

respect source map and `map` option
No
No

fix: respect the `map` option and source maps

---

src/options.json
test/__snapshots__/validate-options.test.js.snap
test/validate-options.test.js

`postcss` can add/change options, we should avoid validate 3rd party options, `postcss` itself should to do it
No
No

refactor: do not validate `postcss` options

---

src/index.js
src/utils.js
test/__snapshots__/config.test.js.snap
test/__snapshots__/postcssOptins.test.js.snap
test/config-autoload.test.js
test/config.test.js
test/fixtures/config-autoload/pkg/package.json
test/fixtures/config-scope/from-to/postcss.config.js
test/postcssOptins.test.js

resolve `from` and `to` to work correctly with `postcss`
Yes
No

fix: resolve `from` and `to` from config and options

---

src/index.js
src/utils.js
test/__snapshots__/sourceMap.test.js.snap
test/sourceMap.test.js

fix: source map generation with the "map" option for `postcss`

---

CHANGELOG.md
README.md

docs: fix the 'postcss-present-env' spelling mistakes

---

package-lock.json
package.json
test/__snapshots__/postcssOptins.test.js.snap
test/fixtures/config-scope/with-config/index.js
test/fixtures/config-scope/with-config/postcss.config.js
test/fixtures/config-scope/with-config/style.css
test/fixtures/plugin/new-api.plugin.js
test/loader.test.js
test/postcssOptins.test.js
test/sourceMap.test.js

compatibility with postcss@8
No
Plugin authors still need refactor code of own plugins

fix: compatibility with `postcss@8`

---

src/Error.js
src/Warning.js
test/__snapshots__/loader.test.js.snap

Refactor error and warning message
No
No

Refactor error and warning message

---

README.md
src/index.js
src/utils.js
test/__snapshots__/postcssOptins.test.js.snap
test/fixtures/config-scope/api/postcss.config.js
test/postcssOptins.test.js

fixes #497
No
Partial compatibility with `postcss-cli` with some limitations, please read https://github.com/webpack-contrib/postcss-loader/issues/497#issuecomment-730359288

feat: partial compatibility with `postcss-cli`

---

README.md

Update README links to [PostCSS options](https://postcss.org/api/#processoptions) as the old link simply redirect to the new site without applying any anchoring
N/A
N/A

Update README link to PostCSS options

---

README.md
src/index.js
src/options.json
test/__snapshots__/implementation.test.js.snap
test/__snapshots__/validate-options.test.js.snap
test/implementation.test.js
test/validate-options.test.js

Ref #510 
I know @alexander-akait said it is out-of-scope, but I needed to write the code anyway. So I figured I'd make the code suitable to upstream and submit it anyway—under the assumption this will be closed.
I'll be publishing my fork as `@phated/postcss-loader` for our use in Storybook until we can make the 7.0 breaking release—at which time, we'll be able to require users to rely on peerDeps and switch back to this upstream project.
Cheers! 🚀

Allow tooling authors to provide custom postcss factory through options

---

.github/workflows/nodejs.yml
package-lock.json
package.json
src/index.js
src/options.json

refactor: drop webpack@4

---

src/index.js
test/__snapshots__/loader.test.js.snap
test/loader.test.js

Allow plugins to register build dependencies to properly handle webpack 5 persistent cache invalidation.
None.
N/A

Add support for registering webpack build dependencies

---

README.md
src/index.js
test/loader.test.js

Added support for registering context and missing dependencies
No
No

Feat: added support for registering context and missing dependencies

---

src/index.js
src/utils.js
test/fixtures/esparser/index.mjs
test/fixtures/esparser/package.json
test/fixtures/esparser/runManual.mjs
test/postcssOptins.test.js

Added support ECMA modules for the `parser`, `stringifier` and `syntax` processOptions
No
No

feat: support ECMA modules for the 'parser', 'stringifier' and 'syntax' processOptions

---

src/index.js
test/loader.test.js

The [PostCSS documentation](https://github.com/postcss/postcss/blob/main/docs/guidelines/runner.md#3-dependencies) has been updated to include a new `dir-dependency` message type. To my understanding of webpack this should be functionally equivalent to the existing `context-dependency`.
**Side note: would it be possible to backport this to postcss-loader v4, so that webpack 4 users can benefit?**
_Please feel free to make any changes to this pull request._

feat: add support for `dir-dependency` message type

---

src/index.js

Same as #524 but for version 4 🥳
I didn't add the other types are these are not standardised, but let me know if you want to add them.

[v4] Add support for `dir-dependency` message type

---

.github/workflows/nodejs.yml

`env.node-version` was undefined (`matrix.node-version` was defined, but never used), therefore the linting used to run in Node.js 14
This trips up my tools which scan which node versions are used in Github workflows :)
None
N/A

ci: fix typo in lint matrix setup

---

README.md

docs: note about webpack version

---

README.md

The `implementation` option is missing in the options table

docs: update the "implementation" option

---

README.md

Fixes deprecated postcss custom plugin examples in README.md as reported in https://github.com/webpack-contrib/postcss-loader/issues/552
None
None

Update postcss custom plugin examples in README.md

---

src/utils.js

Allow to load ESM configuration, tests are impossible due bugs and unstable ESM working in jest, so tested manually
No
Fixes https://github.com/webpack-contrib/postcss-loader/issues/613

fix: support ESM version of `postcss.config.js`

---

README.md

Fix the default value of `config` in docs to match the implementation.
Added a note suggesting to disable automatic `config` for performance reason (for example, in our big monorepo with thousands of css files we see 10-20 second improvement for the big 10 minute build).
None

docs: fix default value of config (#626)

---

src/utils.js

use `cause` to keep original error
No
I am preparing good error reporting for CSS in webpack

fix: use `cause` to keep original errors and warnings

---

package.json
src/index.js
src/utils.js
test/__snapshots__/postcssOptions.test.js.snap
test/postcssOptions.test.js

Do not use `klona` - better perf and less deps
No
No

fix(perf): avoid using `klona` for postcss options

---

package-lock.json
package.json
src/utils.js

regenerate lock file and validate latest version before release
No
No

chore(deps): update before release

---

package.json

Fix https://github.com/webpack-contrib/postcss-loader/issues/678
No
No

feat: add `@rspack/core` as an optional peer dependency

---

src/utils.js
test/config-autoload.test.js
test/fixtures/config-autoload/js/array-esm-js/imports/section.css
test/fixtures/config-autoload/js/array-esm-js/index.css
test/fixtures/config-autoload/js/array-esm-js/index.js
test/fixtures/config-autoload/js/array-esm-js/postcss.config.js
test/fixtures/config-autoload/js/array-mjs/imports/section.css
test/fixtures/config-autoload/js/array-mjs/index.css
test/fixtures/config-autoload/js/array-mjs/index.js
test/fixtures/config-autoload/js/array-mjs/postcss.config.mjs

I'm using a ESM version of postcss config in one of my projects (`postcss.config.mjs`) and noticed that postcss-loader did not pick up the configuration. This fixes that issue.
One of the tests I added need to be run with `NODE_OPTIONS=--experimental-vm-modules` to enable ESM support in `jest`. Flip the test to `it.only` and run:
```
NODE_OPTIONS=--experimental-vm-modules npm run test:only -t 'config-autoload'
```

fix(loadConfig): added fix when loading postcss esm configs
